# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  getopts = {
    pname = "getopts";
    version = "58cf6a17c5feb6447673411836b9d37ef2ed9772";
    src = fetchgit {
      url = "https://github.com/oh-my-fish/plugin-getopts";
      rev = "58cf6a17c5feb6447673411836b9d37ef2ed9772";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-G93q005l5yzV5kK0IFAFsNga/NJNC/tRyYT2tpnCbgw=";
    };
  };
  z = {
    pname = "z";
    version = "85f863f20f24faf675827fb00f3a4e15c7838d76";
    src = fetchgit {
      url = "https://github.com/jethrokuan/z";
      rev = "85f863f20f24faf675827fb00f3a4e15c7838d76";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-+FUBM7CodtZrYKqU542fQD+ZDGrd2438trKM0tIESs0=";
    };
  };
}
