# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  getopts = {
    pname = "getopts";
    version = "58cf6a17c5feb6447673411836b9d37ef2ed9772";
    src = fetchgit {
      url = "https://github.com/oh-my-fish/plugin-getopts";
      rev = "58cf6a17c5feb6447673411836b9d37ef2ed9772";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-G93q005l5yzV5kK0IFAFsNga/NJNC/tRyYT2tpnCbgw=";
    };
  };
}
