[language-server.python-lsp]
command = "pyright-langserver"
config = ""
args = ["--stdio"]

[language-server.nix-lsp]
command = "nil"
args = ["--stdio"]


[language-server.clangd]
command = "clangd"
args = ["--enable-config"]

[[language]]
name = "cpp"
language-servers = ["clangd"]
roots = [".git", "CMakeLists.txt"]
auto-format = true

[[language]]
name = "python"
roots = ["pyproject.toml", "setup.py", "Poetry.lock", ".git"]
auto-format = true
language-servers = ["python-lsp"]
formatter = {command = 'black', args = ["--quiet", "-"]}

[[language]]
name = "nix"
roots = ["flake.nix", ".git"]
language-servers = ["nix-lsp"]
formatter = { command = "nixpkgs-fmt" }
auto-format = true

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "markdown"
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
auto-format = true

[[language]]
name = "hcl"
formatter = { command = 'terraform', args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "tfvars"
formatter = { command = 'terraform', args = ["fmt", "-"] }
auto-format = true
